export const OPEN_ADD_WINDOW = 'OPEN_ADD_WINDOW';
export const OPEN_EDIT_WINDOW = 'OPEN_EDIT_WINDOW';
export const CLOSE_WINDOW = 'CLOSE_WINDOW';

export const SAVE_PROJECT_START = 'SAVE_PROJECT_START';
export const SAVE_PROJECT_SUCCESS = 'SAVE_PROJECT_SUCCESS';
export const SAVE_PROJECT_FAIL = 'SAVE_PROJECT_FAIL';

export const OPEN_PROJECT = 'OPEN_PROJECT';
export const SAVE_PROJECT = 'SAVE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const SET_PROJECT_HOURS = 'SET_PROJECT_HOURS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';


