export const ADD_PROJECT = 'ADD_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const CLOSE_PROJECT = 'CLOSE_PROJECT';

export const OPEN_ADD_WINDOW = 'OPEN_ADD_WINDOW';
export const OPEN_EDIT_WINDOW = 'OPEN_EDIT_WINDOW';
export const CLOSE_WINDOW = 'CLOSE_WINDOW';

export const OPEN_PROJECT = 'OPEN_PROJECT';
export const SAVE_PROJECT = 'SAVE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const SET_PROJECT_HOURS = 'SET_PROJECT_HOURS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';

