export const ADD_PROJECT = 'ADD_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const SAVE_PROJECT = 'SAVE_PROJECT';
export const OPEN_PROJECT = 'OPEN_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';